# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/benfen/untitled1/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 77)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 541, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuBuffer = QtWidgets.QMenu(self.menuBar)
        self.menuBuffer.setObjectName("menuBuffer")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuInit = QtWidgets.QMenu(self.menuBar)
        self.menuInit.setObjectName("menuInit")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionstart_edit = QtWidgets.QAction(MainWindow)
        self.actionstart_edit.setObjectName("actionstart_edit")
        self.actionend_edit = QtWidgets.QAction(MainWindow)
        self.actionend_edit.setObjectName("actionend_edit")
        self.actionbuffer = QtWidgets.QAction(MainWindow)
        self.actionbuffer.setObjectName("actionbuffer")
        self.actionopen_shp = QtWidgets.QAction(MainWindow)
        self.actionopen_shp.setObjectName("actionopen_shp")
        self.actioninit = QtWidgets.QAction(MainWindow)
        self.actioninit.setObjectName("actioninit")
        self.actionlayers = QtWidgets.QAction(MainWindow)
        self.actionlayers.setObjectName("actionlayers")
        self.menuBuffer.addSeparator()
        self.menuBuffer.addAction(self.actionstart_edit)
        self.menuBuffer.addAction(self.actionend_edit)
        self.menuBuffer.addAction(self.actionbuffer)
        self.menuFile.addAction(self.actionopen_shp)
        self.menuInit.addAction(self.actioninit)
        self.menuInit.addAction(self.actionlayers)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuBuffer.menuAction())
        self.menuBar.addAction(self.menuInit.menuAction())
        self.mainToolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuBuffer.setTitle(_translate("MainWindow", "Buffer"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuInit.setTitle(_translate("MainWindow", "Init"))
        self.actionstart_edit.setText(_translate("MainWindow", "start edit"))
        self.actionend_edit.setText(_translate("MainWindow", "end edit"))
        self.actionbuffer.setText(_translate("MainWindow", "buffer"))
        self.actionopen_shp.setText(_translate("MainWindow", "open shp"))
        self.actioninit.setText(_translate("MainWindow", "init"))
        self.actionlayers.setText(_translate("MainWindow", "layers"))

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1346, 608)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

class BufferWin(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Buffer")
        Form.resize(279, 370)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 261, 294))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.verticalLayout.addWidget(self.radioButton_3)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 319, 186, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Buffer"))
        self.label.setText(_translate("Form", "Buffer"))
        self.label_3.setText(_translate("Form", "object type"))
        self.radioButton.setText(_translate("Form", "point"))
        self.radioButton_2.setText(_translate("Form", "line"))
        self.radioButton_3.setText(_translate("Form", "polygon"))
        self.label_2.setText(_translate("Form", "buffer radius"))
        self.label_4.setText(_translate("Form", "name of buffer layer"))
        self.pushButton_2.setText(_translate("Form", "cancel"))
        self.pushButton.setText(_translate("Form", "finish"))

